### ISSUE TITLE
Invalid value for ProFTPD 1.3.6 "TLSStaplingCache" directive

### ISSUE THREAD

**Issue by eomanis** [mozilla/ssl-config-generator#100]
Currently generated:

```
# requires mod_tls_shmcache
TLSStapling                   on
TLSStaplingCache              "shmcb:logs/ssl_stapling(32768)"
```

The `mod_tls_shmcache` [module](http://www.proftpd.org/docs/contrib/mod_tls_shmcache.html) of ProFTPD 1.3.6c does not recognize this value for `TLSStaplingCache`.

A valid value would e.g. be

```
TLSStaplingCache              shm:/file=/tmp/proftpd/ocsp_cache
```

The specified file appears to be used as mutex.

Also, `mod_tls_shmcache` is not required for `TLSStapling on`; the comment should be above the `TLSStaplingCache` directive only.

(`mod_tls_shmcache` extends `mod_tls`' functionality so it can use `shm:...` as values for `TLSStaplingCache` and `TLSSessionCache`.)

**Comment by gene1wood** [comment]
@eomanis Thanks for reporting this. I appreciate it. Fixed in #223 and deployed.
