### ISSUE TITLE
apache: Add RewriteCond for permanent redirect to https to exclude acme challenges

### ISSUE THREAD

**Issue by DG1000** [mozilla/ssl-config-generator#121]
I like to suggest to add the following rewrite condition to the apache ssl configuration for permanent redirect to https

RewriteCond %{REQUEST_URI} "!/.well-known/acme-challenge/"

to exclude acme challenges from rewrite. At least as a comment for users using acme challenges and want to uncomment it.

I know, this is not really an SSL configuration option itself, but it avoids confusion why acme challenges can fail.

**Comment by april** [comment]
My hope is to someday add the ability to check a box for automatic HTTPS via ACME. When I do, this will certainly get added.
