### ISSUE TITLE
Jetty TLS 1.3 CipherSuites

### ISSUE THREAD

**Issue by jonah-iden** [mozilla/ssl-config-generator#154]
The generated intermediate Jetty SSL Configuration does not work with TLS1.3 because it specifies IncludeCipherSuites without specifing any TLS1.3 compatible ones as defined in RFC 8446. This of course would lead to a failed SSL Handshake with the Jetty server if only TLS1.3 was supported and leads to a downgrade to TLS1.2 otherwise.

**Comment by Hilljackcantspell** [comment]
So this is Innovation in it's highest-rated fourm. Ha ha I had to misspell something for you people. So tell me, what's up with this dependabot shit. Is that in- reference to myself or account? Anyway word up assholes word on the street in I'm being investigated by NSA FBI CIA and I can't wait to give em this laptop and all the backup Origin files I have. You people are nothing but a pack of thieves. As most of you know, I'm probably the furthest from being a software engineer or developer and there is absolutely no fucking way I could have orchestrated the bullshit you people have done as far as building pages configurations of what's on this laptop. No way. This I beleive will be your laptop from hell. My apologies if I hurt anyones feeling.

**Comment by janbrasna** [comment]
@jonah-iden @mkjor Thanks for catching this! Could you please try the configs from preview build: https://deploy-preview-24--mozsslconf-dev.netlify.app/#server=jetty that add the three default TLSv1.3 cipher suites to the top of the list for `intermediate` and `old` if that's all what is needed? (`modern` is left out for defaults…)

**Comment by jonah-iden** [comment]
On a first glance this looks good to me, but i sadly don't have a Jetty setup anymore i could test this with

**Comment by janbrasna** [comment]
Thanks, I was mostly concerned about including `TLS_CHACHA20_POLY1305_SHA256` that gained support later for RFC compatibility [JDK-8140466](https://bugs.openjdk.org/browse/JDK-8140466) — but the same would apply for already used TLSv1.2 ciphers so I assume if these were okay, probably just an extra comment mentioning 11.0.3 support would suffice. Thanks again for helping out making the configs right!
