### ISSUE TITLE
Dovecot 2.3.15 supports TLSv1.3

### ISSUE THREAD

**Issue by cmouse** [mozilla/ssl-config-generator#156]
Please add modern config support for dovecot since v2.3.15. See https://doc.dovecot.org/settings/core/#setting-ssl-min-protocol.

Also dovecot does not require ssl_dh setting (or non-ECC DH) since v2.3.3, and can be left out. 

Thanks.

**Comment by gene1wood** [comment]
Thanks @cmouse . Fixed
