### ISSUE TITLE
Move GitHub Pages build and deploy function into GitHub Actions

### ISSUE THREAD

**Issue by gene1wood** [mozilla/ssl-config-generator#161]
Move GitHub Pages build and deploy function into GitHub Actions. Probably also good to move the deploy from `/docs/` to the `gh-pages` branch to avoid all the commits into the codebase which aren't code changes but just deployed artifacts.

**Comment by janbrasna** [comment]
Ultimately you can skip committing to `gh-pages` completely and have the action artifacts deployed to `github-pages` environment without any underlying git history et al., I'll look into some starter workflows for webpack (or just npm) what's usually used today now when the #215 update brings compatibility with newer node runners.

This means that any merged PR goes straight into production. (No need for maintainers to build locally and test — which also means PR preview deployments are much needed alongside this. Too bad GH still hasn't published theirs https://github.com/actions/deploy-pages/issues/180 :/…)
