### ISSUE TITLE
Caddy incorrect syntax for hsts header

### ISSUE THREAD

**Issue by demifiend9** [mozilla/ssl-config-generator#170]
Caddy uses [exact path matchers.](https://caddyserver.com/docs/caddyfile/matchers#syntax)

`header / Strict-Transport-Security "max-age=63072000"` would only match `example.com/` and will not send header in any other url like `example.com/path/`

Removing `/` from the syntax or using `*` will enable the header to be sent on all urls:

`header Strict-Transport-Security "max-age=63072000"` or `header * Strict-Transport-Security "max-age=63072000"`, both are same.

**Comment by janbrasna** [comment]
Will land via #153

**Comment by gene1wood** [comment]
Fixed in #153

**Comment by gene1wood** [comment]
@demifiend9 Thanks for reporting this!
