### ISSUE TITLE
Apache missing OCSP Stapling?

### ISSUE THREAD

**Issue by jrchamp** [mozilla/ssl-config-generator#19]
I expected to find `SSLUseStapling` somewhere in the `apache.hbs` partial, but I could only find it in the `oraclehttp.hbs` partial. For some reason the Oracle one has Apache version numbers in the handlebars file, but the default Oracle version is something like 12 which for some reason makes the template partial think that Oracle 12.2 doesn't support turning `SSLCompression` off. (that's probably a different issue with the version comparison)

@april Thank you so much for all the work you've done to update the generator. Unfortunately, I'm just not sure where to start because I'm not familiar with what would be the correct details for the Oracle partial.

**Comment by april** [comment]
Yeah, I ripped out a bunch of the Oracle stuff today. Their documentation is _horrendous_, and it's impossible to determine what a correct configuration should look like.

I'll look into the OCSP stapling thing!
