### ISSUE TITLE
Obsolete or non adequate formulations in comments about components required by Apache

### ISSUE THREAD

**Issue by Ricky-Tigg** [mozilla/ssl-config-generator#195]
**build** e6bc57e | Hello. In the comments of Apache configurations are mentioned required components upon model `mod_<name>`.

In Fedora | Available and installed packages:
```
$ dnf -q list mod_{rewrite,headers,socache_shmcb,ssl}
Installed Packages
mod_ssl.x86_64        1:2.4.56-1.fc38        @fedora
```
Investigation to figure out whether non-reported packages –whose existence is implied by their mentions in those very comments– can be revealed:
```
$ httpd -M | grep -E 'rewrite|headers|socache_shmcb|ssl' | column
 headers_module (shared)	 socache_shmcb_module (shared)
 rewrite_module (shared)	 ssl_module (shared)
```
 Then, as it appears, required components formulated in comments as `mod_rewrite`, `mod_headers` and `mod_socache_shmcb` do not exist as package names on my system. That indicates a need for updating relevant comments accordingly.

Suggestion | `# (...) requires those components that may depending of the Linux distribution be present either as packages or as part of an httpd package: mod_ssl, mod_socache_shmcb, mod_rewrite, and mod_headers.`

**Comment by tomato42** [comment]
>  which would not be healthy for the project owner.

????
