### ISSUE TITLE
Config for old client (TLS 1.0 / 1.1) won't work, for (at least) HAProxy 2.4.

### ISSUE THREAD

**Issue by lvergergsk** [mozilla/ssl-config-generator#206]
https://ssl-config.mozilla.org/#server=haproxy&version=2.4&config=old&openssl=1.1.1k&guideline=5.7

Comparing `intermediate` config with `old` config, you removed `no-tlsv10 no-tlsv11`, but this actually does not allow `TLS 1.0` and `TLS 1.1`. You will need to add `ssl-min-ver TLSv1.0` for this to work.

You can try it use `curl --tlsv1.0 --tls-max 1.0 ...`

**Comment by gene1wood** [comment]
@lvergergsk When you use the config that you link to in HAProxy, does HAProxy throw an error (can you share what the error is if it does)?

Can you tell me more about the `curl` line you start? Are you saying that HAProxy accepts the configuration but something wrong can be seen when you run a `curl` command?

**Comment by lvergergsk** [comment]
@gene1wood 
There was no error log in haproxy and the error produced by the curl command is below:


```
curl --tlsv1.0 --tls-max 1.0 https://xxx.xxx.com/
curl: (35) OpenSSL/1.1.1t: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
```

To clearfy, the point I intend to make is following:
Comparing the `intermediate` and `old` config, I think your config is trying to allow `TLS 1.0` and `TLS 1.1` for those old client.
On the other hand, the value of `ssl-min-ver` is default to TLSv1.2 as decribed [in HAProxy doc](https://docs.haproxy.org/2.4/configuration.html#5.1-ssl-min-ver).
Hence we will fail to use `TLS 1.0` and `TLS 1.1` to connect the server with described HAProxy config.

I added `ssl-min-ver TLSv1.0` to my server and this fixed old client server and the test curl command.

**Comment by lvergergsk** [comment]
Actually `ssl-min-ver` and `ssl-max-ver` is preferred over `no-tlsv...` option from HAProxy 2.x.

**Comment by janbrasna** [comment]
It was buggy before 2.2 https://github.com/haproxy/haproxy/commit/2e8d52f869ed7673a8274ec7b045161e09350251 see https://github.com/haproxy/haproxy/issues/595 — so the question is… if that gets changed to ssl-min/max-ver, should that be behind haproxy version conditional, or such bug in the server should not be  polluting the config definition? (Thing is… if the configuration doesn't get picked up, is it safe to provide it as a recommendation?)

**Comment by janbrasna** [comment]
@lvergergsk What you're suggesting to force-enable TLSv1.1-v1.2 is to change the configs (for 2.0+ or 2.2+ see above) along the lines:


```diff
    # intermediate configuration
-    ssl-default-bind-options prefer-client-ciphers no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
+    ssl-default-bind-options prefer-client-ciphers no-tls-tickets ssl-min-ver TLSv1.2
-    ssl-default-server-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
+    ssl-default-server-options no-tls-tickets ssl-min-ver TLSv1.2
```
(↑ this one has no impact, but needs v2+)

```diff
    # old configuration
-    ssl-default-bind-options no-sslv3 no-tls-tickets
+    ssl-default-bind-options no-tls-tickets ssl-min-ver TLSv1.0
-    ssl-default-server-options no-sslv3 no-tls-tickets
+    ssl-default-server-options no-tls-tickets ssl-min-ver TLSv1.0
```

to force lower TLS version than current default to cater to `old` clients?

**Comment by gstrauss** [comment]
HandleBar is somewhat deficient as a template parser as HandleBar does not cleanly support compound conditional logic without duplication of contents.

**Comment by gstrauss** [comment]
In #275, I am going to modify haproxy.hbs to use `ssl-min-ver` for HAProxy 2.2 and later.

Even if the haproxy patch referenced by @janbrasna in https://github.com/mozilla/ssl-config-generator/issues/206#issuecomment-1867867680 was backported to HAProxy 1.8, the current https://docs.haproxy.org/ notes that everything prior to HAProxy 2.2 (LTS) is EOL.

https://docs.haproxy.org/1.8/configuration.html#5 documents that even HAProxy 1.8 recognizes `ssl-min-ver`, but I am not going to bother checking the code for 1.8.0, and @janbrasna noted there was a usage bug in HAProxy until HAProxy 2.2.
