### ISSUE TITLE
Add support for IANA cipher names

### ISSUE THREAD

**Issue by april** [mozilla/ssl-config-generator#21]
In addition to OpenSSL.  :)

**Comment by april** [comment]
This should help @captn3m0 with Traefix and @mholt with Caddy.

**Comment by mholt** [comment]
Awesome; we're switching to the IANA names in Caddy 2.

**Comment by april** [comment]
Fixed in 8e726dbbad1aec5c95e76d1f90c1b0836b9058f7.

**Comment by mholt** [comment]
FYI, Caddy 2 (still in development, so no need to update this tool for now) now uses only the standard IANA names: https://github.com/caddyserver/caddy/commit/28df6cedfe8d347bd87931960c01e6606c14851e
