### ISSUE TITLE
Support "ffdhe1024" for Old

### ISSUE THREAD

**Issue by april** [mozilla/ssl-config-generator#22]
Instead of 2048, as it uses now.

**Comment by tomato42** [comment]
for 1024 bit, the parameters really should be generated new for every server, so hosting doesn't work for that

**Comment by april** [comment]
Hmmmmm, that's a good point.

**Comment by april** [comment]
This is pushed. It should recommend `openssl dhparam` for 1024-bits and ffdhe2048 for 2048-bits.

**Comment by tomato42** [comment]
nice, thanks!
