### ISSUE TITLE
Postfix 3.7+ custom DH params discouraged on OpenSSL 3

### ISSUE THREAD

**Issue by wolegis** [mozilla/ssl-config-generator#238]
See https://www.postfix.org/postconf.5.html section **smtpd_tls_dh1024_param_file**

> With Postfix ≥ 3.7, built with OpenSSL version is 3.0.0 or later, if the parameter value is either empty or "auto", then the DH parameter selection is delegated to the OpenSSL library, which selects appropriate parameters based on the TLS handshake. This choice is likely to be the most interoperable with SMTP clients using various TLS libraries, and custom local parameters are no longer recommended when using Postfix ≥ 3.7 built against OpenSSL 3.0.0.

**Comment by gstrauss** [comment]
Included in #256 is a change for Postfix 3.7+ and OpenSSL 3.0.0+

**Comment by janbrasna** [comment]
> "custom local parameters are no longer recommended"

Well, I believe they mean random arbitrary params, those are def not recommended — but I see no mention of that option being deprecated or anything alike — it's still perfectly fine to use it and provide the safe primes as we do now.

I'd much rather control the groups than leave that to RFC 7919 negotiation allowing #162 bad performance:/

EDIT: Ah, okay, sane defaults here, luckily: https://www.postfix.org/postconf.5.html

> **tls_ffdhe_auto_groups** (default: see "postconf -d" output)
> 
> The prioritized list of finite-field Diffie-Hellman ephemeral (FFDHE) key exchange groups supported by the Postfix SMTP client and server. OpenSSL 3.0 adds support for FFDHE key agreement in TLS 1.3. In OpenSSL 1.1.1, TLS 1.3 was only supported with elliptic-curve based key agreement. The "tls_ffdhe_auto_groups" parameter makes it possible to configure the list of FFDHE groups that the Postfix client or server will enable in OpenSSL 3.0 and up. This parameter has no effect when Postfix is built against earlier OpenSSL versions.
> 
> The **default list of FFDHE groups that Postfix enables in OpenSSL 3.0 and up includes just the 2048 and 3072-bit groups**. Stronger FFDHE groups perform poorly and EC groups are a much better choice for the same security level. Postfix ignores group names that are unknown to OpenSSL, or that are known but not yet implemented. The FFDHE groups are largely a backup, in case some peer does not support EC key exchange, or EC key exchange needs to be disabled for some pressing reason.

So no need to set, the defaults are reasonably small. (And, eventually can be set empty to disallow FFDHE for TLSv1.3 if deemed necessary in the future, or as a pattern for OpenSSL 3.x compatibility in #256?)

**Comment by gstrauss** [comment]
Scope of #256 has been reduced.  Given that postfix is documented to enable only 2048 and 3072-bit groups for FFDHE for TLSv1.3, we may choose to switch postfix to use DH auto selection (recently removed from PR #256), though not if we choose to disable all FFDHE groups fro TLSv1.3.
