### ISSUE TITLE
Disable TLS session tickets in Apache

### ISSUE THREAD

**Issue by bmw** [mozilla/ssl-config-generator#24]
If this change was discussed somewhere and done on purpose I'm sorry for the noise, but I noticed the new generated Apache config no longer disables TLS session tickets. Shouldn't this still be done for the same reason it's done in the generated nginx config? According to [Apache's documentation](https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslsessiontickets) it compromises forward secrecy unless you regularly restart the server.

**Comment by april** [comment]
It wasn't a purposeful decision, just an oversight that has now been fixed. Tickets can be implemented safely, but in a world where Apache and nginx don't make it safe by default, they should be disabled.

Thankfully this entire mess is fixed in TLS 1.3.

**Comment by ekr** [comment]
Well, mostly.

Say you do a full handshake in connection 1 and dispense ticket T_1, encrypted with key K.  At this point there is no exposure for that client if K is compromised.

If the client then connects to the server and does 0-RTT with T_1, but then negotiates PSK-DH, and then T_2 is dispensed, encrypted with K. At this point if K is compromised, then the 0-RTT data is also compromised but the 1-RTT is not.

**Comment by april** [comment]
Thanks, @ekr!

@bmw, one option for this could be to simply leave them disabled but with a note on how to enable them safely.

That said, I think that's a good idea. I suspect that the handful of people who know how to enable them safely will do so, and I don't want a bunch of people toggling them to `on` without understanding or implementing proper key sanitation.

**Comment by bmw** [comment]
For what it's worth, I agree with you that simply leaving the TLS session tickets disabled in Apache until their implementation is improved is probably the safest thing to do.

There's less of a need for this every day, but I think it may be worth updating the config generator to only disable TLS session tickets if the selected version of Apache supports the directive. Support was added in Apache [2.2.30](https://httpd.apache.org/docs/2.2/mod/mod_ssl.html#sslsessiontickets) and [2.4.11](https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslsessiontickets) which are ancient, however, RHEL 6 has Apache 2.2.15 and [Debian 8 has Apache 2.4.10](https://packages.debian.org/jessie/apache2) which are both still supported until next year.

**Comment by april** [comment]
I did guard around 2.2.30 and 2.4.11 this morning, as someone else had reported the bug.  :)
