### ISSUE TITLE
Change AWS CloudFormation to YAML

### ISSUE THREAD

**Issue by gene1wood** [mozilla/ssl-config-generator#26]

**Comment by acdha** [comment]
It might be better to reference https://github.com/awslabs/aws-cfn-template-flip (or maybe use that to automatically support both formats?) since there are valid arguments for both formats and no single choice is going to work for everyone.

**Comment by gene1wood** [comment]
> no single choice is going to work for everyone

Agreed. For the moment we'll go with YAML as it should be easier to read but indeed the user can can use cfn-flip to convert it to JSON if they wish

> maybe use that to automatically support both formats

A PR for that would likely be accepted
