### ISSUE TITLE
Revisit Dovecot `ssl_dh` between versions

### ISSUE THREAD

**Issue by janbrasna** [mozilla/ssl-config-generator#265]
I think we may have introduced a gap for v2.3.3+

https://github.com/mozilla/ssl-config-generator/blob/ea1349ddc1f3d57baa58cb61638bb4038e56ba2e/src/templates/partials/dovecot.hbs#L7-L15

(i.e. it reads… `{{#if (minver "2.3.3" form.serverVersion)}} # do nothing`…)

But that's not exactly what I can infer from:

> > "Since v2.3.3+ Diffie-Hellman parameters have been made optional, and you are encouraged to disable non-ECC DH algorithms completely."
> — [doc.dovecot.org/configuration_manual/dovecot_ssl_configuration](https://doc.dovecot.org/configuration_manual/dovecot_ssl_configuration/#ssl-security-settings)
> 
> This sounds to me as removing `ssl_dh` should go hand in hand with disabling `DHE-*` cipher suites, which only applies with `modern` configuration.

 — _Originally posted by @janbrasna in https://github.com/mozilla/ssl-config-generator/pull/175#pullrequestreview-1802406095_

That was in response to a previously required value:

> What _might be needed_ is between v2.3–v2.3.3 adding the dhparams to the output always, unconditionally even when no DHE suites are present, as the docs state:
> 
> > "From version 2.3, you must specify path to DH parameters file using:"
> 
> (which is somewhat ambiguous, it's not clear from the docs that one must specify the path only if interested in own dhparams, or simply _always_…)

 — _Originally posted by @janbrasna in https://github.com/mozilla/ssl-config-generator/pull/175#discussion_r1441041149_

**Comment by gstrauss** [comment]
Looking at the Dovecot code, if an attempt is made to use a non-ECC DH algorithm and `ssl_dh` is not set in the config, the code will error out.
```
        e_error(ssl_io->event, "Diffie-Hellman key exchange requested, "
                "but no DH parameters provided. Set ssl_dh=</path/to/dh.pem");
```
(There are multiple paths to support old versions of openssl, and I did not carefully follow them all)

It does look like this change for #156 should be reverted, as this change was ancillary to the issue of marking Dovecot version which supports TLSv1.3 in Dovecot.

**Comment by janbrasna** [comment]
@gstrauss Thank you so much for looking up the actual behavior and confirming we only need to include it for our existing _usesDhe_ condition… +1, reverting ^
