### ISSUE TITLE
IMHO a bug in apache configuration

### ISSUE THREAD

**Issue by DG1000** [mozilla/ssl-config-generator#308]
In my humble opinion in the configuration `Intermediate` and `Old` the plus (`+`) is missing in front of every protocol:

So instead of

`SSLProtocol             TLSv1.2 TLSv1.3`

it should be

`SSLProtocol             +TLSv1.2 +TLSv1.3`

With the first one I have connection issues from a Windows 10 .Net client to my linux server, with modified one it works.

**Comment by gstrauss** [comment]
What version of Apache?

> With the first one I have connection issues from a Windows 10

Please describe.  Are you able to provide more details than "something went wrong"?

Please test with this:
`SSLProtocol             -ALL +TLSv1.2 +TLSv1.3`

That should be equivalent to:
`SSLProtocol             TLSv1.2 TLSv1.3`

What you posted which works for you is effectively not specifying `SSLProtocol` at all since Apache by default includes `All`

**Comment by DG1000** [comment]
> What version of Apache?

2.4.58 on Ubuntu 24.04, OpenSSL 3.0.13

> > With the first one I have connection issues from a Windows 10
> 
> Please describe. Are you able to provide more details than "something went wrong"?

I receive "SSL connection could not be established" and as an inner exception "Authentication failed because the remote party sent a TLS alert: 'ProtocolVersion'."

> Please test with this: `SSLProtocol -ALL +TLSv1.2 +TLSv1.3`
> 

Works fine.

> That should be equivalent to: `SSLProtocol TLSv1.2 TLSv1.3`
> 

This gives the errors above.

> What you posted which works for you is effectively not specifying `SSLProtocol` at all since Apache by default includes `All`

You are right, the "-all" was missing.

**Comment by gstrauss** [comment]
`SSLProtocol -all +TLSv1.2 +TLSv1.3` appears to be better-accepted by Apache, even if more obtuse than setting MinProtocol on other servers.  I'll make the above change shortly.  Thank you, @DG1000, for the bug report.

---

Does your Apache error log have something along the lines of the following?
```
"%s: Protocol '%s' overrides already set parameter(s). "
"Check if a +/- prefix is missing.",
```

If so, you might check to see why your Windows 10 machines are not trying to use TLSv1.3.

**Comment by DG1000** [comment]
Thank you @gstrauss for the discussion and change. I found this line in the log:

`SSLProtocol: Protocol 'TLSv1.3' overrides already set parameter(s). Check if a +/- prefix is missing.`

For the moment I am unsure why there is/was such an issue with the application on Windows 10, because on Windows 11 there is no problem. TLSv1.2 and TLSv1.3 are both enabled in the application.
But with the change to `SSLProtocol -all +TLSv1.2 +TLSv1.3` it now works again, so there is no need for me to spend more time.
