### ISSUE TITLE
Proposal to enhance apache2 configuration

### ISSUE THREAD

**Issue by DG1000** [mozilla/ssl-config-generator#310]
I like to propose enhancement of apache2 configuration. As mentioned here https://httpd.apache.org/docs/trunk/ssl/ssl_howto.html in section _How can I create an SSL server which accepts strong encryption only?_ ssl compression should be disabled to prevent attacks (see link to wikipedia):

`SSLCompression off`

The option `SSLSessionTickets off` is already part of the configuration, but I would like to see a short comment why it should be configured like this.

So my proposal is to modify/enhance like this:

```
# prevent oracle attacks, see https://en.wikipedia.org/wiki/CRIME
SSLCompression off

# prevent compromise of PFS
SSLSessionTickets off
```

**Comment by gstrauss** [comment]
TLS compression has long been deprecated is disabled by default in modern TLS libraries.

TLS session tickets are safe to use when accepting only PFS ciphers and when there is a session ticket encryption key rotation scheme configured, but these might not be the case in older servers or TLS libraries.

Some servers provide default session ticket encryption key rotation, and that works fine for single servers, but there is more complexity involved to coordinate session ticket encryption key rotation across multiple server instances, machines, and locations in order have highest session resumption success.  This is all well beyond the scope of a one or two line comment in a configuration file.

I wrote some more technical details for lighttpd at https://wiki.lighttpd.net/Docs_SSL#Session-Tickets
