### ISSUE TITLE
Add support for dovecot?

### ISSUE THREAD

**Issue by D4N** [mozilla/ssl-config-generator#33]
Hi, thanks for this great tool!

Would you consider adding support for dovecot? It has a pretty extensive documentation about TLS: https://wiki.dovecot.org/SSL/DovecotConfiguration, it only lacks a nice template for lazy people (like me).

**Comment by april** [comment]
If you can send me some good templates of working configurations, I would love to add them.  :)

**Comment by D4N** [comment]
Unfortunately I don't run dovecot in production, so I don't have a
working configuration.
