### ISSUE TITLE
wrong option for nginx modern and intermediate

### ISSUE THREAD

**Issue by MagicChocoRolls** [mozilla/ssl-config-generator#34]
When creating an nginx config, for intermediate and modern the generator always tells  me to set `ssl_prefer_server_ciphers off;`.
This seems weird. I would assume this should always be set to 'on'!?

**Comment by april** [comment]
Nope, it should be `off` for Intermediate and Modern. We talk about why this is here:

https://wiki.mozilla.org/Security/Server_Side_TLS

**Comment by teward** [comment]
@april erm... if you DO talk about this in that document, it's not clear *where* it's stated.

Current version of the document says this:

> The ordering of cipher suites in the Intermediate and Old configurations is very important, as it determines the priority with which algorithms are selected.

... which means for Intermediate, ordering is **still necessary**.  Which means your documentation and the generator are in disagreement.

**Comment by april** [comment]
Ahh, it's just the wiki that's off. I'll remove the Intermediate bit from it. Thanks.

**Comment by april** [comment]
There, all fixed.  :)

**Comment by april** [comment]
It should be noted that the JSON document and Intermediate section (in multiple places) talk about why Client Ordered is preferred, it was just that paragraph at the top was incorrect.

The generator has always been correct.

**Comment by gene1wood** [comment]
@april thanks for fixing the wiki with mozilla/server-side-tls#262 and @teward thanks so much for catching this inconsistency that was likely to trip up other people as well.
