### ISSUE TITLE
Configuration direct download

### ISSUE THREAD

**Issue by JGoutin** [mozilla/ssl-config-generator#35]
The idea is to add the possibility to directly download the raw configuration file instead of show the full web page.

Example, if I use the URL: `https://ssl-config.mozilla.org/#server=nginx&server-version=1.17.0&config=modern&format=raw` this output directly the Nginx 1.17.0 modern configuration file as text file.

So, I can use it as base in script or other automated tools to generate the full configuration file.

**Comment by april** [comment]
The trick with this is that there is no web server or anything running; the entire configuration file is generated in JavaScript in real time. I could have the JavaScript change the entire page to plaintext, but scripts wouldn't be able to see that outside of Selenium.  :(

**Comment by JGoutin** [comment]
OK. So I'll look if I can do something directly with templates, Python and [this library](https://github.com/wbond/pybars3) (Handlebars.js for Python). Thanks.
