### ISSUE TITLE
Nginx redirect - duplicated query parameters

### ISSUE THREAD

**Issue by lynt-smitka** [mozilla/ssl-config-generator#37]
The “http to https” redirect rule will double GET parameters in the final URL:

return 301 https://$host$request_uri;

http://example.com?utm_x=y => https://example.com?utm_x=y?utm_x=y

The right rule should be:

return 301 https://$host$request_uri?;

It might cause various problems e.g. with the analytics.

More about this issue (in Czech language, sorry) https://lynt.cz/blog/nezvladnute-presmerovani

**Comment by april** [comment]
I'm not sure I understand. I have a system with this configuration and:

http://example.com?utm_x=y

Redirects me to:

https://example.com?utm_x=y

Is there some other thing that's adding the analytics twice? Seems like that code is the problem. The redirect should happen before any JavaScript loads. This rule seems much worse, as it would redirect:

http://example.com/ => https://example.com/?

**Comment by lynt-smitka** [comment]
Sorry, my fault. There is "return" in the generator, the question mark is necessary for "rewrite". https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#taxing-rewrites

**Comment by april** [comment]
In that section, nginx explicitly recommends the current way of redirecting over your method. I'm pretty sure the rule that is there – it is the one recommended almost everywhere – is the correct rule. 

If you're having problems with analytics, I would look at your library to see if it's doing something wrong. But in all my years of testing, the existing rule has never doubled any of the query parameters.
