### ISSUE TITLE
Add TLSv1.3 configuration

### ISSUE THREAD

**Issue by eternaltyro** [mozilla/ssl-config-generator#4]
If OpenSSL version is `1.1.1b` or later, for supported servers, please include configuration for TLSv1.3.

TLS v1.3 and consequently OpenSSL support 5 cipher suites
```
TLS_AES_256_GCM_SHA384
TLS_CHACHA20_POLY1305_SHA256
TLS_AES_128_GCM_SHA256
TLS_AES_128_CCM_8_SHA256
TLS_AES_128_CCM_SHA256
```
The first three suites are included by default even if no Cipher preference is included. Optionally, they can be included in the cipher suite if TLSv1.2 is also required like so:
```
ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers 'TLS-CHACHA20-POLY1305-SHA256:TLS-AES-256-GCM-SHA384:TLS-AES-128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384: ....';
```

### Reference:
1. OpenSSL Notes: https://wiki.openssl.org/index.php/TLS1.3

**Comment by april** [comment]
This is blocked by:

https://github.com/mozilla/server-side-tls/issues/178

The generator doesn't do many (or any) manual tweaks, it simply sets what is defined in the Mozilla specification. I definitely agree that it should be on there.
