### ISSUE TITLE
haproxy config causes haproxy 2.x to hang in http/2 mode with unverified curl

### ISSUE THREAD

**Issue by sandys** [mozilla/ssl-config-generator#40]
curl -D- -k  -L https://1.2.3.4/test -H "Host: abc.com" results in a hang with haproxy setup in http/2 mode. I'm using haproxy 2.0

this is the full config https://ssl-config.mozilla.org/#server=haproxy&server-version=1.9.8&config=modern

commenting out 
# ssl-default-server-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
# ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets

makes it work again

**Comment by april** [comment]
Did you have a version of `curl` that supports TLS 1.3? The Modern configuration is explicitly for TLS 1.3 clients only; otherwise, we would recommend that you use Intermediate.

**Comment by sandys** [comment]
hi @april - thanks for replying. I understand what you are saying, but your configuration results in a hang. Not your fault, maybe upstream's fault...but nevertheless it has a potential to bring down servers. 

would you be able to do a configuration for TLS 1.3 that results in a connection reject/error in haproxy ? that is still acceptable.

**Comment by april** [comment]
It's not upstreams fault, you've simply configured haproxy to use a configuration that's likely incompatible with your old clients. The webpage explicitly talks about this.

If you use the intermediate configuration, do you still have problems? All of the configurations (modern, intermediate, old) support TLS 1.3 if your haproxy/openssl versions are new enough. You don't need to use modern to get TLS 1.3.

**Comment by sandys** [comment]
hi @april 	
those are not *my* clients. they are clients from the public internet who are attempting a connecting to me and causing a hang (which is exhausting my connection pool). 

i want to use modern configuration and categorically reject anybody who is on a client that does not support your configuration. i have a publicly exposed server - i really cannot control who connects to me. 
it would be awesome if you could generate a configuration that is safe for me to use inspite of potentially malicious clients.

**Comment by april** [comment]
This is why the website says Modern is for when *you* can control the clients. Intermediate says this:

> General-purpose servers with a variety of clients, recommended for almost all systems

Right on the webpage. When you made the choice to use Modern, you asserted that you could control the clients when you couldn't. Change your configuration to Intermediate and you should not have any issues.

**Comment by sandys** [comment]
![Screenshot from 2019-07-12 20-21-19](https://user-images.githubusercontent.com/76883/61137178-acca1600-a4e2-11e9-9472-57386e5d689d.png)
umm it doesnt say that i have to have control over the clients. generally the language is understood to mean that "other clients will be rejected" versus "other clients can cause your server to hang"

but ill defer to your wont-fix. thanks for your patience.

**Comment by april** [comment]
If clients are causing haproxy to hang, you should open up a bug with them. There shouldn't ever be circumstances where clients are able to hang the server.

**Comment by april** [comment]
I just setup haproxy with this configuration, on https://ssl-config-test.badsite.io/

```
global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private

        ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
        ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11 no-tlsv12 no-tls-tickets

        ssl-default-server-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
        ssl-default-server-options no-sslv3 no-tlsv10 no-tlsv11 no-tlsv12 no-tls-tickets

frontend ft_test
    mode    http
    bind    :443 ssl crt /etc/lego/certificates/ssl-config-test.badsite.io.haproxy.pem alpn h2,http/1.1
    bind    :80
    redirect scheme https code 301 if !{ ssl_fc }


defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http
```

And I wasn't able to get the server to hang at all, no matter what I did.
