### ISSUE TITLE
Stray curly brace in HAProxy config

### ISSUE THREAD

**Issue by DrewBloechl** [mozilla/ssl-config-generator#42]
The generated HAProxy config has what looks like a stray `}` in the generated output (at least when rendered as "intermediate"), and HAProxy rejects it as invalid.

I see a corresponding `}` in the haproxy.hbs template on line 25 -- I suspect this just needs to be replaced with a blank line.

Thanks for making this service!

**Comment by april** [comment]
Whoops, thanks for letting me know! I've got that fixed.  :)

**Comment by hkrutzer** [comment]
Looks like it is still there on https://ssl-config.mozilla.org/#server=haproxy&server-version=1.9.8&config=modern

**Comment by april** [comment]
Looks like there were two of them, and I only removed one. I've now super duper fixed things.  :)

**Comment by gene1wood** [comment]
Here's the other one April removed : bf3edd186faceb4088240c2fc68d634e7ea90342
