### ISSUE TITLE
Surface version of config generator on page

### ISSUE THREAD

**Issue by gene1wood** [mozilla/ssl-config-generator#46]
If this is already present and I couldn't find it then this request is more about making it easier to find.

Let's surface the version of the config generator that's running within the config generator page, or if there's no appetite for versioning the releases of the config generator (which I'm assuming since we don't have version git tags or github releases), let's surface the git commit of the version of code that was used to build the config generator.

I suspect it would help with issues like #42 where it looks like the code was fixed 6 days ago but hasn't been deployed to the live site and so there's a delta between the code repo and the site so the behavior implied by the code isn't yet manifested on the site.

This could be done in the footer of the page, maybe with the short form of the commit hash linked to the commit URL in GitHub.

**Comment by april** [comment]
That had nothing to do with issue #42; there were actually two stray curly braces and I only managed to remove one.

**Comment by april** [comment]
(as far as I know, there has only been a significant gap between what's pushed and what's built once or twice, and it has never blocked fixes)

**Comment by gene1wood** [comment]
What do you think about the idea though unrelated to #42?

**Comment by april** [comment]
It's probably fine, although I'm not sure how frequently it would get used. I'll work on it in a bit.  :)

**Comment by april** [comment]
Fixed in 7a88c75.  :)
