### ISSUE TITLE
HAProxy config uses ciphers string as ciphersuites

### ISSUE THREAD

**Issue by DrewBloechl** [mozilla/ssl-config-generator#47]
In https://github.com/mozilla/ssl-config-generator/commit/6517d7321aa17cf2d0abd21886742023d441229f, the HAProxy template was changed so that ssl-default-*-ciphersuites comes from the ciphers variable, but this is not a valid value for this setting:

```
[ALERT] 202/212644 (1) : Proxy 'https-in': unable to set TLS 1.3 cipher suites to 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384' for bind '*:443' at [/etc/haproxy/haproxy.cfg:28].
[ALERT] 202/212644 (1) : Fatal errors found in configuration.
```

The last-known-working value I had was `TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256`.

**Comment by april** [comment]
Oh, whoops! Thanks, I'll get that fixed.

**Comment by april** [comment]
Okay, should be fixed. Lemme know if you run into any issues with it, thanks!
