### ISSUE TITLE
Add 'preload' to HSTS header?

### ISSUE THREAD

**Issue by mrphs** [mozilla/ssl-config-generator#50]
I wonder if there should be another checkbox in the "Miscellaneous" section to enable HSTS preload. IIRC, it was included in the past. Was there a reason to remove it? Or maybe I'm just misremembering.

**Comment by april** [comment]
I don't believe we've ever included `preload`, given how badly you can make your subdomains inoperable. Even if we had done that, I certainly wouldn't add it now.  :)

But thanks for checking in!
