### ISSUE TITLE
Intermediate config for Traefik contains invalid ciphersuites

### ISSUE THREAD

**Issue by EwoutIO** [mozilla/ssl-config-generator#52]
Hi, thanks for this tool to provide us with decent configuration, I would be lost without it!
I was figuring out which cipher suites to use for Traefik, so I used the tool to generate a list of suites. This caused problems during the starting of a new instance of Traefik in a container.

Steps to reproduce:
1. Create a new ssl-config for Traefik, with the intermediate setting
1. Start a traefik-container with the given cipher suites.

The container will log errors that the following cipher suites are not recognized as valid:
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256

I checked the Go documentation, and found that the cipher suites aren't mentioned there either. Relatively close alternatives were mentioned however:
https://godoc.org/crypto/tls#pkg-constants

By replacing the cipher suites with their closest matches, I was able to get it to work.

| Old Value | New Value |
| --- | --- |
| TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 | TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305 |
| TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 | TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 |
| TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 | TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 |
| TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 | TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 |

As I do not have the experience or knowledge to assess whether these are good substitutes for each other, I cannot propose a solution or fix for this problem, other than adjusting the values for the Traefik configuration.

**Comment by thommy101** [comment]
Hi, I've also just ran into this.
It looks like the first two are misnamed in Go acording to https://github.com/golang/go/issues/32061
The last two you mentioned and their corresponding new value are already in the default intermediate list. Go decided to not implement TLS_DHE (https://github.com/golang/go/issues/7758#issuecomment-274376902).

**Comment by april** [comment]
Blarg, thanks for letting me know.

**Comment by april** [comment]
Okay, I've got this all fixed in the latest version. It does contain a warning about how you should use ECDHE certificates with Traefik, due to the Go limitations.
