### ISSUE TITLE
Cipher suites for TLSv1.3?

### ISSUE THREAD

**Issue by mrphs** [mozilla/ssl-config-generator#53]
I just noticed while Server Side TLS guideline for [Modern compatibility](https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility) recommends the following cipher suites for TLSv1.3, the config generator doesn't include them. At least not for Nginx + Modern config. 

`TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256`

**Comment by jrchamp** [comment]
Most software that supports TLSv1.3 does not specify the available encryption options using the traditional cipher string settings. In general, when TLS 1.3 is enabled, all of the available options that are approved for TLS 1.3 are enabled, because currently, all of them are good. This means that you typically do not need to included them in the cipherlist configuration, because they're already on. Hope that helps!

**Comment by april** [comment]
Yep, exactly right. Most software doesn't even expose a way to configure the order.  :)

**Comment by robkorv** [comment]
The `ssl_ciphers` is still wrong for Intermediate though. When using https://ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=intermediate&openssl=1.1.1d&guideline=5.4 there is no TLS 1.3 cipher to make a 1.3 connection to the nginx server. They should be included in the `ssl_ciphers` list.

**Comment by april** [comment]
That's not true at all.

https://www.ssllabs.com/ssltest/analyze.html?d=ssl-config-test.badsite.io

Is running the Intermediate profile exactly, and you can see that it's supporting TLS 1.3 perfectly fine without having to add anything to `ssl_ciphers`. It is completely unnecessary.

**Comment by robkorv** [comment]
@april you are right. It did some further testing and it seems there is something else wrong with my stack that is not related to `ssl_ciphers`. I still don't get a TLS 1.3 connection if I only use `ssl_protocols TLSv1.3;` with or without the ciphers. I'll hide my stuff as "Off topic".

**Comment by april** [comment]
I haven't had any problems with the Modern configuration that does exactly that. I've tested that in nginx as well.
