### ISSUE TITLE
HAProxy 1.5.19 fails to start due to ssl-dh-param-file

### ISSUE THREAD

**Issue by cherouvim** [mozilla/ssl-config-generator#55]
Source configuration URL: https://ssl-config.mozilla.org/#server=haproxy&server-version=1.5.19&config=old&openssl-version=1.1.0h

Restarting HAProxy gives me:
```
 * Reloading haproxy haproxy
[ALERT] 234/140714 (8555) : parsing [/etc/haproxy/haproxy.cfg:21] : unknown keyword 'ssl-dh-param-file' in 'global' section
[ALERT] 234/140714 (8555) : Fatal errors found in configuration.
```

My versions are:
```
$ openssl version
OpenSSL 1.1.0h  27 Mar 2018 (Library: OpenSSL 1.1.1b  26 Feb 2019)

$ haproxy -V
HA-Proxy version 1.5.19 2016/12/25
Copyright 2000-2016 Willy Tarreau <willy@haproxy.org>
```

Yes, I know, that HAProxy is very old. But I still have a system with that specific version, and the `ssl-config-generator` ideally should not suggest the usage of `ssl-dh-param-file`.

Also, commenting out the `ssl-dh-param-file` line, caps my "Overall rating" to `B` in https://www.ssllabs.com/ssltest/ due to dhparam and to solve this I have to add:
```
tune.ssl.default-dh-param 2048
```

**Comment by tomato42** [comment]
in which version of HAProxy was the `ssl-dh-param-file` directive added?

**Comment by cherouvim** [comment]
For sure it exists in 1.6. Not sure about the patch version though.

**Comment by april** [comment]
Looks like it was added in pre-1.6.0, so I've gone ahead and so I've gone ahead and fixed things. Thanks!
