### ISSUE TITLE
comment incorrectly says mod_socache_shmcb required

### ISSUE THREAD

**Issue by yeahforbes** [mozilla/ssl-config-generator#56]
The generated config at https://ssl-config.mozilla.org/#server=apache&server-version=2.4.6&config=intermediate&openssl-version=1.0.2k-fips&hsts=false&ocsp=false includes a comment "# requires mod_ssl and mod_socache_shmcb" but I believe mod_socache_shmcb is actually not required, due to ocsp=false.

**Comment by april** [comment]
Thanks for letting me know about this!
