### ISSUE TITLE
Dovecot 2.2.27: Unknown setting ssl_min_protocol

### ISSUE THREAD

**Issue by xrat** [mozilla/ssl-config-generator#58]
https://ssl-config.mozilla.org/#server=dovecot&server-version=2.2.27&config=intermediate suggests `ssl_min_protocol = TLSv1.2` but with this Dovecot 2.2.27 fails to start:
```
Unknown setting: ssl_min_protocol
```

**Comment by tomato42** [comment]
any idea in which version was that option added?

**Comment by xrat** [comment]
From [Upgrading Dovecot v2.2 to v2.3](https://wiki2.dovecot.org/Upgrading/2.3)

> `ssl_protocols` setting was replaced by `ssl\_min\_protocol`. Now you only specify the minimum ssl protocol version Dovecot accepts, defaulting to TLSv1.

**Comment by april** [comment]
Thanks for letting me know! I'll take a look at this!

**Comment by april** [comment]
Should be all fixed now. Lemme know if the new code doesn't work for your installation.  :)

**Comment by xrat** [comment]
Just tried + tested it. All good. Thanks a lot!
