### ISSUE TITLE
Advise dynamic dh parameters instead of downloading from mozilla

### ISSUE THREAD

**Issue by italovalcy** [mozilla/ssl-config-generator#60]
Dear all,

When configuring nginx with intermediate configuration, the comments about dhparameters says:

```
    # curl https://ssl-config.mozilla.org/ffdhe2048.txt > /path/to/dhparam.pem
    ssl_dhparam /path/to/dhparam.pem;
```

IMO it is more appropriated to use a dynamic dh generated parameters, such as:

```
    # openssl dhparam -out /path/to/dhparam.pem  2048
    ssl_dhparam /path/to/dhparam.pem;
```

This would be more secure as well as keep it simple.

Regards, italo

**Comment by tomato42** [comment]
> IMO it is more appropriated to use a dynamic dh generated parameters

you can't use custom DH parameters in TLS 1.3...

no, custom parameters are not needed, the only time when they are appropriate is when you need compatibility with systems that don't support parameters bigger than 1024 bit. With emphasis on need, as they are not secure any more

**Comment by xrat** [comment]
@tomato42  For now, ssl-config-generator still provides settings for more than just TLS 1.3.
Apart from that I, too, thought that generating once own DH parameters was recommended.

**Comment by tomato42** [comment]
my point is that TLS 1.3 is a new protocol, one we designed after having more than two decades of additional experience with designing cryptographic protocols, one that received multiple formal analyses when it was in draft stage, and in it, the ability for server to choose DH parameters completely arbitrarily was removed

yes, sharing the same parameters between multiple servers makes attacking all of them computationally cheaper, *but* it requires those parameters to be actually breakable in the first place (reused parameters make them a more rewarding target, not an easier target) – see https://weakdh.org/imperfect-forward-secrecy-ccs15.pdf especially section 5

**Comment by april** [comment]
We recommend generating your own parameters for sizes less than 2048 (as you'll see if you select "Old"), but we use the standard FFDHE parameters for 2048. They are more compatible, and there aren't concerns about their security.

Note that standard DHE is a small (and shrinking) portion of handshakes and likely won't even be recommended in the next version of the standards.
