### ISSUE TITLE
Dovecot all but Old have `ssl_prefer_server_ciphers = no`

### ISSUE THREAD

**Issue by j-be** [mozilla/ssl-config-generator#65]
I'm not sure why this is a bug or intended. Dovecot documentation (https://wiki.dovecot.org/SSL/DovecotConfiguration) under "SSL security settings" states:

> You should usually prefer server ciphers and their order, so setting
> `ssl_prefer_server_ciphers=yes`
> is recommended.

If there is a good reason for not doing it, I would suggest adding a comment describing why.

**Comment by XelNika** [comment]
From [the wiki](https://wiki.mozilla.org/Security/Server_Side_TLS):

>  The cipher suites are all strong and so we allow the client to choose, as they will know best if they have support for hardware-accelerated AES

**Comment by j-be** [comment]
I see, that makes sense. Would you accept a pull request adding something like the following?

```handlebars
[ ... ]

{{#unless output.serverPreferredOrder}}
# The cipher suites are all strong and so we allow the client to choose, as they will know best if they have support for hardware-accelerated AES
{{/unless}}
ssl_prefer_server_ciphers = {{#if output.serverPreferredOrder}}yes{{else}}no{{/if}}
```

**Comment by april** [comment]
I appreciate the offer, but I'd rather not add this to (essentially) every configuration file, as it's more comments and stuff I have to maintain and upkeep. 😅

**Comment by j-be** [comment]
Fair enough. Closing.
