### ISSUE TITLE
Support GitHub Releases

### ISSUE THREAD

**Issue by siccovansas** [mozilla/ssl-config-generator#68]
It would be awesome if this repo could create a release for each new 'Server Side TLS' version. This would allow people to use the 'watch releases only' functionality of GitHub which sends you an email as soon as a new release is available. I would really like this functionality as there is currently no easy way to be updated of new versions of 'Server Side TLS'.

**Comment by april** [comment]
I think this is a good idea, but I don't think it would be a good place to have here, even though it's the official store of the JSON configurations.

I'll start doing over at https://github.com/mozilla/server-side-tls, however. Thanks!
