### ISSUE TITLE
Postgresql below 10 (9.6, 9.5, etc) do not support ssl_dh_params_file

### ISSUE THREAD

**Issue by saepurusass** [mozilla/ssl-config-generator#70]
ssl_dh_params_file parameter is first mentioned in PostgreSQL 10 documentation:
https://www.postgresql.org/docs/10/runtime-config-connection.html

Using this parameter in older versions will break configuration and PostgeSQL will not start with error message that says ssl_dh_params_file is unknown parameter.

Configurator suggest ssl_dh_params_file for every PostgreSQL version.
It should not suggest this parameter for PostgreSQL versions lower than 10.

**Comment by april** [comment]
Thanks for letting me know! I'll try to get that fixed up tomorrow.  :)

**Comment by april** [comment]
Fixed and pushed to prod. Thanks so much for letting me know!
