### ISSUE TITLE
huge feature request: browser compatibility matrix

### ISSUE THREAD

**Issue by chipitsine** [mozilla/ssl-config-generator#73]
it would be really nice to see which browsers (and other popular clients) will work with generated config.

currently, the usual way is

1. generate config
2. apply it
3. go to SSL Labs and see whether all required browsers are supported or not

it would be nice to see matrix right after config is generated

**Comment by april** [comment]
It shows you directly above the configuration which browsers are compatible. Or am I missing something?

**Comment by chipitsine** [comment]
I mean "handshake simulation" 
https://www.ssllabs.com/ssltest/analyze.html?d=ssl%2dconfig.mozilla.org&s=185.199.111.153&latest


yep, currently it shows very briefly like "Supports Firefox 27, Android 4.4.2, Chrome 31, Edge, IE 11 on Windows 7, Java 8u31, OpenSSL 1.0.1, Opera 20, and Safari 9"

it is not clear about the rest, what is supported, what is not.

**Comment by april** [comment]
What do you mean "the rest"? The browser list is based exactly on SSL Lab's handshake list.

**Comment by chipitsine** [comment]
I mean, as a website owner, I'd like to have the whole picture, including all browsers. like SSL Labs does. Not very brief like currently Mozilla SSL Config does.

**Comment by april** [comment]
I don't think there will be anything more "whole picture" than a huge swath of information about supported browsers. It's pretty complete for the vast majority of people, and what SSL Labs has took many years of development effort.  :)

**Comment by april** [comment]
Oh, it has occurred to me that maybe you're not completely understanding this:

> Supports Firefox 27, Android 4.4.2, Chrome 31, Edge, IE 11 on Windows 7, Java 8u31, OpenSSL 1.0.1, Opera 20, and Safari 9

This means that it supports any of those web browsers _and newer_. It's basically every operating system used in the last five years.  :)
