### ISSUE TITLE
Inconsistent server ssl-config.mozilla.org configuration

### ISSUE THREAD

**Issue by makhomed** [mozilla/ssl-config-generator#74]
Inconsistent server ssl-config.mozilla.org configuration
![ssl-config mozilla org](https://user-images.githubusercontent.com/5003666/72387990-7e492400-372d-11ea-9d5c-0e86b33c07f1.png)
![ssl-config mozilla org-185 199 108 153](https://user-images.githubusercontent.com/5003666/72388116-c0726580-372d-11ea-9121-786aa524c492.png)

**Comment by april** [comment]
ssl-config.mozilla.org runs out of github pages, so unfortunately this isn't something we really have control over.  :(

**Comment by april** [comment]
(thank you for letting me know, though!)

**Comment by makhomed** [comment]
Already fixed:

![ssl-config mozilla org 2020-01-15](https://user-images.githubusercontent.com/5003666/72466882-726b6980-37e2-11ea-97fb-5eb281cd1a48.png)

**Comment by april** [comment]
Oh cool, thanks for checking in on it again.  :)
