### ISSUE TITLE
Enable Google Analytics

### ISSUE THREAD

**Issue by gene1wood** [mozilla/ssl-config-generator#8]
The old generator had Google Analytics enabled. Let's add it to the new generator when we cutover (enable the redirects on the old generator).

Here's the code

https://github.com/mozilla/server-side-tls/pull/234/files#diff-368131f28b06d0d830e9140e471682f9R651

**Comment by april** [comment]
Note to self: this will need to be reworked in order to work with the new generator's content security policy.

**Comment by april** [comment]
@gene1wood, are these analytics actually used by anyone that you know of?

**Comment by gene1wood** [comment]
In the past with the product being a skunworks thing, only me/infosec consumed the metrics to my knowledge.

With this becoming part of the observatory etc suite of tools, it sounds like it would be of more value.

Do you ask because implementing GA is difficult with the new tool?

**Comment by april** [comment]
More than I don't want to add tracking unless it's necessary. I don't believe the Observatory has analytics itself, mostly because there hasn't been anyone to consume them in a useful way.

**Comment by gene1wood** [comment]
In this new era of looking for premium service opportunities I suspect there will be value in having metrics of some kind.

**Comment by april** [comment]
I did add a good chunk of the code in 48d9703aa48113345ca216aaa090d6f5e64f6f1d, without enabling it. That said, does this really make sense when:

a) Firefox now blocks it by default, and
b) Apparently the old site hasn't been successfully collecting analytics for a very long period of time

**Comment by IanLee1521** [comment]
FWIW, it appears that the analytics are embedded in the main https://ssl-config.mozilla.org/ page, though they are configured differently from what is done in @april 's 48d9703 commit... Maybe make them the same once it is worked out whether they should be there at all?

https://github.com/mozilla/server-side-tls/blob/12fda41dca6e31451fe45023f219439d420513e5/ssl-config-generator/index.html#L650-L658

**Comment by april** [comment]
Those analytics are for the old, no longer supported page. As far as I know, they haven't worked for a long time.

The current page does not have any analytics at the moment.

**Comment by gene1wood** [comment]
> Apparently the old site hasn't been successfully collecting analytics for a very long period of time

The old site has been collecting metrics correctly up through today. What are you seeing that makes it seem like it's not?

> That said, does this really make sense when:

Yes, it does make sense to add it. Do please enable it.

**Comment by april** [comment]
Okay, as near as I can tell it is generating analytics. I'm not sure if I'm doing it correctly, but at least some pings are coming into GA.
