### ISSUE TITLE
Intermediate Config generation for dovecot 2.0.9

### ISSUE THREAD

**Issue by langemar** [mozilla/ssl-config-generator#85]
Hi,

the intermediate configuration for dovecot 2.0.9 with openssl 1.0.1e (RHEL 6.10) does not work with Thunderbird 68.4.1 (Archlinux, openssl 1.1.1d).

Dovecot gives the error
```
Feb 29 10:58:58 **** dovecot: imap-login: Disconnected (no auth attempts): rip=****, lip=****, TLS handshaking: SSL_accept() failed: er
ror:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
```

best regards

**Comment by tomato42** [comment]
That shouldn't happen, RHEL 6 version of OpenSSL supports TLS 1.2 and modern ciphers (AES-GCM).

Can you make a packet capture and show what ciphers are advertised in Thunderbird's ClientHello?

**Comment by langemar** [comment]
Hi,

TLSv1,2 is working fine.
With the given parameters the generator tell's modern configuration is not supported.
And using the intermediate configuration Thunderbird can't connect due to the error message above.

Client Hello say's:
Cipher Suites (18 suites)
    Cipher Suite: TLS_AES_128_GCM_SHA256 (0x1301)
    Cipher Suite: TLS_CHACHA20_POLY1305_SHA256 (0x1303)
    Cipher Suite: TLS_AES_256_GCM_SHA384 (0x1302)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)
    Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca9)
    Cipher Suite: TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca8)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)
    Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (0xc00a)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (0xc009)
    Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)
    Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)
    Cipher Suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA (0x0033)
    Cipher Suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA (0x0039)
    Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA (0x002f)
    Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA (0x0035)
    Cipher Suite: TLS_RSA_WITH_3DES_EDE_CBC_SHA (0x000a)

best regards

**Comment by tomato42** [comment]
> TLSv1,2 is working fine.

I think something got lost in translation: if it's working fine, why you've filed the issue?

> `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256`

Thunderbird is advertising the cipher it should end up negotiating

and the OpenSSL, as I've said, supports it

so it looks to me like the issue is on dovecot side; likely the ECDHE patches from 2.2.5 were not backported https://dovecot.org/doc/NEWS-2.3 :
```
v2.2.5 2013-08-05  Timo Sirainen <tss@iki.fi>

	+ SSL: Added support for ECDH/ECDHE cipher suites (by David Hicks)
	+ Added some missing man pages (by Pascal Volk)
```
please contact Red Hat support about this, they will be able to say if it is indeed the case

a possible workaround would be to add `DHE-RSA-AES128-SHA` to cipherstring in dovecot

**Comment by langemar** [comment]
I'd filed the issue because it's not working with the cipher suite list provided by the generator.
Using a different cipher suite list with TLSv1.2 enabled works.

Thanks for your hint about dovecot, I'll check that soon.

best regards

**Comment by april** [comment]
This is good to have this ticket, but I don't think I'm going to be able to do much to fix it. I could come up with an alternative cipher suite list, but ECDHE is _super_ old and this was support that was added seven years ago.

At a certain point it doesn't make sense to make special cases for ancient software, unfortunately.

Thanks again for pointing this out, should other people in your situation head over here.  :)
