### ISSUE TITLE
Include Redis open-source in configuration generator

### ISSUE THREAD

**Issue by IAmATeaPot418** [mozilla/ssl-config-generator#86]
Redis open-source 6 will include many TLS enhancements in its upcoming release.

I'm happy to submit a PR with the guidance but is there any process or guidelines to help accomplish this or a review process?

I'm looking mostly for acceptance criteria so I can bake it into the PR.

**Comment by april** [comment]
You can learn the process to add new software here:

https://github.com/mozilla/ssl-config-generator#adding-new-software

**Comment by IAmATeaPot418** [comment]
@april I've submitted https://github.com/mozilla/ssl-config-generator/pull/87 to add support for Redis.

LMK what you think. Please don't merge this yet. This version is not GA and the release candidate is still being tested.
