### ISSUE TITLE
Would it better to wrap "return 301" inside a `location` block of nginx conf?

### ISSUE THREAD

**Issue by runapp** [mozilla/ssl-config-generator#95]
I've recently found that [acme.sh](https://github.com/acmesh-official/acme.sh) cannot auto renew a domain hosted by nginx and using the configure file generated by this tool. After some inspection, I found acme.sh is just adding a block like 

```
location ~ "^/\.well-known/acme-challenge/([-_a-zA-Z0-9]+)$" {
  default_type text/plain;
  return 200 "I AM THE TOKEN";
}
```

to the `listen 80` server block. However, cause the `return 301` is under the main `server` block, no other blocks won't override that.

I'm not sure if the best way is to make a change to acme.sh project, or conf template of this tool? From my point of view, default action seems to be always inside a `location /` block. But on the other side, it's acme.sh who should take more care to be compatible with more cases. Any ideas?

**Comment by april** [comment]
I think that would probably make sense to me. Sorry for taking so long to respond to this!
