### ISSUE TITLE
Invalid value for ProFTPD 1.3.6 "TLSProtocol" directive

### ISSUE THREAD

**Issue by eomanis** [mozilla/ssl-config-generator#99]
Currently generated:
```
TLSProtocol                   TLSv1.2 TLSv1.3
```

As of ProFTPD 1.3.6, the `mod_tls` module of ProFTPD does not appear to recognize `TLSv1.3` as a valid protocol string for the `TLSProtocol` directive.
This will [presumably be fixed](https://github.com/proftpd/proftpd/issues/536) with ProFTPD 1.3.7.

A workaround is to allow all protocols and blacklist the undesired ones:
```
TLSProtocol                   ALL -SSLv3 -TLSv1 -TLSv1.1
```

**Comment by gene1wood** [comment]
It looks like [`TLSv1.3` support was added in `1.3.7rc1`](https://github.com/proftpd/proftpd/blob/eaec6a0f713a360b4a0aabb8aa1d3878056277a4/NEWS#L199)

**Comment by eomanis** [comment]
You are right, it is fixed in ProFTPD 1.3.7.
Can confirm with ProFTPD 1.3.7a and `TLSProtocol TLSv1.2 TLSv1.3` on Arch Linux (`proftpd-2:1.3.7a-3`).

Sorry, I forgot about this issue being open.

**Comment by gene1wood** [comment]
Oh I didn't mean that this was invalid. I suspect there will be users who come to the SSL config generator that are using Proftpd 1.3.6

For example these distros which are currently supported aren't on 1.3.7 yet
Ubuntu up to 20.04
RHEL up to 7

I was just adding some details for myself or someone else to work on a PR with.

**Comment by janbrasna** [comment]
Just simple version update #213 should fix this issue.

@gene1wood Good point with the versions though. `TLSProtocol` is supported from 1.2.7rc1 yet is not behind a version test. Would it be better if that's also added only for ≥1.2.7 and completely left out for older?
